name: CI/CD for Alertlocal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Start services
      run: |
        echo "USERNAME=testuser" >> .env
        echo "PASSWORD=testpass" >> .env
        docker-compose up -d --build

    - name: Install testing tools
      run: |
        sudo apt-get update
        sudo apt-get install -y curl apache2-utils phpunit jq

    - name: Run tests
      run: |
        chmod +x test_alertlocal.sh
        ./test_alertlocal.sh
      env:
        USERNAME: testuser
        PASSWORD: testpass

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-logs
        path: |
          alertlocal/test.log
          alertlocal/*_performance.log

    - name: Stop services
      run: docker-compose down