name: Foundation IO CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        env: [dev, test, prod]
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose php-cli unzip curl nodejs npm jq
          curl -sS https://getcomposer.org/installer | php && sudo mv composer.phar /usr/local/bin/composer
      - name: Lint Script
        run: shellcheck deploy.sh
      - name: Run Deploy
        run: ./deploy.sh ${{ matrix.env == 'prod' && 'prod' || 'local' }}
      - name: Build and Test Containers
        working-directory: ./deploy/${{ matrix.env == 'prod' && 'foundation.io' || 'localhost' }}/${{ matrix.env }}
        run: |
          docker-compose up -d --build
          timeout 60s bash -c "until docker-compose ps | grep -q 'Up'; do sleep 5; done"
          docker-compose down -v
      - name: Run Laminas Tests
        working-directory: ./deploy/${{ matrix.env == 'prod' && 'foundation.io' || 'localhost' }}/src
        run: |
          composer install
          vendor/bin/phpunit --configuration ../../tests/phpunit.xml